FROM maven:3.9-eclipse-temurin-17 AS build
COPY .. /app
RUN mvn clean package -DskipTests
COPY /app/target /target
FROM openjdk:17-jdk-slim

COPY --from=build /target/ecom-website-0.0.1-SNAPSHOT.jar ecom-website.jar